services:
  backend:
    build:
      context: ./app  # Root direktori proyek
      dockerfile: Dockerfile  # Dockerfile backend di root
    container_name: fastapi-backend
    environment:
      DATABASE_URL: "postgresql://postgres:hanif230805@db:5432/soulmate_db"
      MODEL_PATH: "./sentiment_model" 
      SECRET_KEY: "580de766a6923d4f2d2d6a2427758bfe9c59b1eda26581cb3235c9cb3c3e34c"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
      PYTHONPATH: "/app"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./sentiment_model:/app/sentiment_model
      - ./app:/app
    working_dir: /app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend
    restart: always
   
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hanif230805
      POSTGRES_DB: soulmate_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d  # ← Tambahkan baris ini


volumes:
  postgres_data:
